project_name: supercronic

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - DOCKER_CLI_EXPERIMENTAL=enabled

release:
  prerelease: auto
  draft: false
  github:
    owner: dckrz
    name: supercronic

snapshot:
  name_template: "{{ .Version }}{{ if .IsSnapshot }}-snapshot{{ else if .IsNightly }}-nightly{{ end }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

signs:
  - artifacts: checksum
    stdin: '{{ .Env.GPG_PASSPHRASE }}'
    args:
      - "--batch"
      - "--no-tty"
      - "--local-user={{ .Env.GPG_FINGERPRINT }}"
      - "--output=${signature}"
      - "--detach-sign"
      - "--passphrase-fd=0"
      - "--pinentry-mode=loopback"
      - "${artifact}"

builds:
  - id: supercronic
    main: ./
    binary: supercronic
    goos:
      - linux

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - "6"
      - "7"

    ldflags:
      - -s -w
      - -X 'github.com/dckrz/supercronic/version.version={{.Version}}'
      - -X 'github.com/dckrz/supercronic/version.gitCommit={{.ShortCommit}}'
      - -X 'github.com/dckrz/supercronic/version.projectName=supercronic'
      - -X 'github.com/dckrz/supercronic/version.projectURL=https://github.com/dckrz/supercronic'

dockers:
  - &docker_build
    goos: linux
    goarch: amd64
    ids:
      - supercronic
    skip_push: "false"
    use: buildx

    image_templates:
      - &docker_tag_amd64 "ghcr.io/dckrz/supercronic:{{ .Tag }}-amd64"
      - &docker_major_amd64 "ghcr.io/dckrz/supercronic:v{{ .Major }}-amd64"
      - &docker_major_minor_amd64 "ghcr.io/dckrz/supercronic:v{{ .Major }}.{{ .Minor }}-amd64"
      - &docker_latest_amd64 "ghcr.io/dckrz/supercronic:latest-amd64"

    build_flag_templates:
      - "--platform=linux/amd64"
      - &build_flag_tmpl_date "--label=org.opencontainers.image.created={{.Date}}"
      - &build_flag_tmpl_name "--label=org.opencontainers.image.name={{.ProjectName}}"
      - &build_flag_tmpl_commit "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - &build_flag_tmpl_version "--label=org.opencontainers.image.version={{.Version}}"
      - &build_flag_tmpl_url "--label=org.opencontainers.image.source={{.GitURL}}"

    dockerfile: Dockerfile.goreleaser

  - <<: *docker_build
    goarch: arm
    goarm: "6"
    image_templates:
      - &docker_tag_arm32v6 "ghcr.io/dckrz/supercronic:latest-arm32v6"
      - &docker_major_arm32v6 "ghcr.io/dckrz/supercronic:{{ .Tag }}-arm32v6"
      - &docker_major_minor_arm32v6 "ghcr.io/dckrz/supercronic:v{{ .Major }}-arm32v6"
      - &docker_latest_arm32v6 "ghcr.io/dckrz/supercronic:v{{ .Major }}.{{ .Minor }}-arm32v6"

    build_flag_templates:
      - "--platform=linux/arm"
      - *build_flag_tmpl_date
      - *build_flag_tmpl_name
      - *build_flag_tmpl_commit
      - *build_flag_tmpl_version
      - *build_flag_tmpl_url

  - <<: *docker_build
    goarch: arm
    goarm: "7"
    image_templates:
      - &docker_tag_arm32v7 "ghcr.io/dckrz/supercronic:latest-arm32v7"
      - &docker_major_arm32v7 "ghcr.io/dckrz/supercronic:{{ .Tag }}-arm32v7"
      - &docker_major_minor_arm32v7 "ghcr.io/dckrz/supercronic:v{{ .Major }}-arm32v7"
      - &docker_latest_arm32v7 "ghcr.io/dckrz/supercronic:v{{ .Major }}.{{ .Minor }}-arm32v7"

    build_flag_templates:
      - "--platform=linux/arm/v7"
      - *build_flag_tmpl_date
      - *build_flag_tmpl_name
      - *build_flag_tmpl_commit
      - *build_flag_tmpl_version
      - *build_flag_tmpl_url

  - <<: *docker_build
    goarch: arm64
    image_templates:
      - &docker_tag_arm64v8 "ghcr.io/dckrz/supercronic:latest-arm64v8"
      - &docker_major_arm64v8 "ghcr.io/dckrz/supercronic:{{ .Tag }}-arm64v8"
      - &docker_major_minor_arm64v8 "ghcr.io/dckrz/supercronic:v{{ .Major }}-arm64v8"
      - &docker_latest_arm64v8 "ghcr.io/dckrz/supercronic:v{{ .Major }}.{{ .Minor }}-arm64v8"

    build_flag_templates:
      - "--platform=linux/arm64"
      - *build_flag_tmpl_date
      - *build_flag_tmpl_name
      - *build_flag_tmpl_commit
      - *build_flag_tmpl_version
      - *build_flag_tmpl_url

docker_manifests:
  - name_template: "ghcr.io/dckrz/supercronic:latest"
    image_templates:
      - *docker_latest_amd64
      - *docker_latest_arm32v6
      - *docker_latest_arm32v7
      - *docker_latest_arm64v8
  - name_template: "ghcr.io/dckrz/supercronic:{{ .Tag }}"
    image_templates:
      - *docker_tag_amd64
      - *docker_tag_arm32v6
      - *docker_tag_arm32v7
      - *docker_tag_arm64v8
  - name_template: "ghcr.io/dckrz/supercronic:v{{ .Major }}"
    image_templates:
      - *docker_major_amd64
      - *docker_major_arm32v6
      - *docker_major_arm32v7
      - *docker_major_arm64v8
  - name_template: "ghcr.io/dckrz/supercronic:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - *docker_major_minor_amd64
      - *docker_major_minor_arm32v6
      - *docker_major_minor_arm32v7
      - *docker_major_minor_arm64v8
